routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/news', 'NewsController@index')->name('news');
Route::get('/interview', 'InterviewController@index')->name('interview');
Route::get('/opinions', 'OpinionsController@index')->name('opinions');
Route::get('/today', 'TodayController@index')->name('today');

Route::get('/banking', 'BankingController@index')->name('banking');
Route::get('/insurance', 'InsuranceController@index')->name('insurance');
Route::get('/credits', 'CreditsController@index')->name('credits');
Route::get('/deposits', 'DepositsController@index')->name('deposits');
Route::get('/cards', 'CardsController@index')->name('cards');

Route::get('/monitoring', 'MonitoringController@index')->name('monitoring');
Route::get('/blockchain', 'BlockchainController@index')->name('blockchain');
Route::get('/mining', 'MiningController@index')->name('mining');
Route::get('/trading', 'TradingController@index')->name('trading');
Route::get('/statistics', 'StatisticsController@index')->name('statistics');

Route::get('/services', 'ServicesController@index')->name('services');
Route::get('/exchanges', 'ExchangesController@index')->name('exchanges');
Route::get('/aggregators', 'AggregatorsController@index')->name('aggregators');
Route::get('/contacts', 'ContactsController@index')->name('contacts');



Route::group(['middleware' => ['auth'], 'as' => 'client.', 'prefix' => '/client'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/send-request', 'RequestController@sendRequest')->name('send.request');
    Route::post('/mark-as-read/{id}', 'RequestController@markAsReadById')->name('mark.as.read');
});

resources/views/partials/contact-form.blade.php
@error('upload')
    <div class="form-group row">
        <div class="col">
            <span class="invalid-feedback d-block" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        </div>
    </div>
@enderror
<form method="POST" action="{{ route('client.send.request') }}" enctype="multipart/form-data">
    @csrf
    <div class="form-group row">
        <label for="subject" class="col-md-4 col-form-label text-md-right">{{ __('layout.subject') }}</label>
        <div class="col-md-6">
            <input id="subject" type="text" class="form-control @error('subject') is-invalid @enderror" name="subject" value="{{ old('subject') }}" required autocomplete="subject" autofocus maxlength="100">
            @error('subject')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="message" class="col-md-4 col-form-label text-md-right">{{ __('layout.message') }}</label>
        <div class="col-md-6">
            <textarea id="message" type="text" class="form-control @error('message') is-invalid @enderror" name="message" required maxlength="1000"> {{ old('message') }}</textarea>
            @error('message')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="file" class="col-md-4 col-form-label text-md-right">{{ __('layout.add-file') }}</label>
        <div class="col-md-6">
            <input id="file" type="file" name="file" class="inputfile @error('file') is-invalid @enderror" />
{{--            <label for="file">Выберите файл</label>--}}
            @error('file')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row mb-0">
        <div class="col-md-8 offset-md-4">
            <button type="submit" class="btn btn-outline-success">
                {{ __('layout.send') }}
            </button>
        </div>
    </div>
</form>

resources/views/partials/users-requests-list.blade.php
@if(!empty($list))
    <div class="col list-wrapper">
        <div class="card">
            <div class="card-header">
                {{ __('layout.contact-form') }}
            </div>
            <div class="card-body">
                <hr>
                <div class="form-group row">
                    <div class="col-1">
                        <h4>ID</h4>
                    </div>
                    <div class="col-1">
                        <h4>Имя</h4>
                    </div>
                    <div class="col-2">
                        <h4>E-Mail</h4>
                    </div>
                    <div class="col-2">
                        <h4>Тема</h4>
                    </div>
                    <div class="col message-container">
                        <h4>Сообщение</h4>
                    </div>
                    <div class="col-1">
                        <h4>Файл</h4>
                    </div>
                    <div class="col green">
                        <h4>Статус</h4>
                    </div>
                </div>
                <hr>
                @foreach($list as $item)
                    <?php /** @var \App\Models\UserRequest $item */ ?>
                    <div class="form-group row">
                        <div class="col-1">
                            {{ $item->id }}
                        </div>
                        <div class="col-1">
                            {{ $item->user->name }}
                        </div>
                        <div class="col-2">
                            {{ $item->user->email }}
                        </div>
                        <div class="col-2">
                            {{ $item->subject }}
                        </div>
                        <div class="col message-container">
                            {{ $item->message }}
                        </div>
                        <div class="col-1">
                            @if($item->file_path)
                                <a href="{{ $item->file_path }}" target="_blank">
                                    Файл
                                </a>
                            @endif
                        </div>
                        @if($item->is_answered)
                            <div class="col green">
                                {{ __('layout.answered') }}
                            </div>
                        @else
                            <div class="col">
                                <form method="POST" action="{{ route('client.mark.as.read', ['id' => $item->id]) }}">
                                    @csrf
                                    <button type="submit" class="btn btn-outline-success">
                                        {{ __('layout.mark-as-answered') }}
                                    </button>
                                </form>
                            </div>
                        @endif
                    </div>
                    <hr>
                @endforeach
                {{ $list->links() }}
            </div>
        </div>
    </div>
@endif